feat: add class task management + csv path from config
dataforgoodfr/12_bloom pull request #138
Opened 2024-03-24 20:12 UTC by rv2931

L'idée est d'intégrer la proposition de gestion des tâches sur la base d'une classe BaseTask permettent de lancer des tâches et groupes de tâches de manière simple mais tracées avec gestion des erreurs et envoi d'email

2024-03-26 21:12 UTC, njouanin commented
j'ai l'erreur suivante lorsque je lance le traitement init.py:
```
Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/src/tasks/init.py", line 2, in <module>
    from tasks.data import LoadAmpDataTask, LoadPortDataTask, LoadVesselsDataTask, LoadVesselPositionsDataTask
ImportError: cannot import name 'LoadVesselPositionsDataTask' from 'tasks.data' (/Users/nicolasjouanin/Dev/python/bloom/12_bloom/src/tasks/data/__init__.py)
```

2024-03-26 21:17 UTC, njouanin commented on src/tasks/base.py
> +    def temperature(self, value:bool) -> None:
pourquoi cette méthode s'appelle temperature ?

2024-03-26 21:20 UTC, rv2931 commented on src/tasks/base.py
> +    def temperature(self, value:bool) -> None:
mauvais copier/coller je pense

2024-03-26 21:24 UTC, njouanin requested changes

2024-03-26 21:24 UTC, njouanin commented on src/tasks/data/load_amp_data.py
ancien traitement qui devrait disparaitre et remplacé par `load_dim_zone_amp_from_csv.py`

2024-03-26 21:24 UTC, njouanin commented on src/tasks/data/load_port_data.py
ancien traitement qui devrait disparaitre et remplacé par `load_dim_port_from_csv.py`

2024-03-26 21:24 UTC, njouanin commented on src/tasks/data/load_vessels_data.py
ancien traitement qui devrait disparaitre et remplacé par`load_dim_vessel_from_csv.py`

2024-03-26 21:24 UTC, njouanin commented on src/tasks/facts/load_vessel_positions_data.py
ancien traitement

2024-03-26 21:24 UTC, njouanin commented on src/tasks/load_dimensions.py
> +        LoadPortDataTask(*args,**kwargs).start()
Plutôt `LoadDimPortFromCsv`

2024-03-26 21:24 UTC, njouanin commented on src/tasks/dimensions/load_dim_zone_amp_from_csv.py
Code non repris dans la gestion de tâche

2024-03-26 21:24 UTC, njouanin commented on src/tasks/load_dimensions.py
Ce traitement devrait lancer les 3 traitements de chargement des dimentsions : post, zone_amp et vessels

2024-03-26 21:25 UTC, rv2931 commented
corrigé pour la tâche init, en fait je voulais la supprimer au profit de LoadDimensions et LoadFacts, mais au final ça peut avoir un sens que Init appelle Loaddimensions et LoadFacts donc je l'ai laissée et mise à jour

2024-03-26 21:27 UTC, rv2931 commented
Oui, je voulais que tu regardes pour me dire quels traitement étaient toujours d'actualité et lesquels potentiellement pourrait grouper dans un LoadDimensions, LoadFacts, PipelineXXX et éventuel Init

2024-03-26 21:28 UTC, njouanin commented
> Oui, je voulais que tu regardes pour me dire quels traitement étaient toujours d'actualité et lesquels potentiellement pourrait grouper dans un LoadDimensions, LoadFacts, PipelineXXX et éventuel Init

pour l'instant j'avais laissé les anciens traitements. Mais en gros tout ce qui charge directement du CSV vers des tables en passant par Dataframe est à supprimer.

2024-03-26 21:29 UTC, rv2931 commented
Hésite pas à propose une autre répartition logique
Là j'ai fait
* tasks/dimensions
* tasks/facts
* tasks/transformations
et mis les pipelines groupés à la racine de tasks mais c'est qu'une proposition

2024-03-26 21:29 UTC, njouanin commented
et `convert_spire_vessels_to_spire_ais_data.py` ne devrait servir qu'une fois (en prod) pour convertir les données de l'ancienne table de positions vers la nouvelle.

2024-03-26 21:31 UTC, njouanin commented
> Hésite pas à propose une autre répartition logique Là j'ai fait
> 
>     * tasks/dimensions
> 
>     * tasks/facts
> 
>     * tasks/transformations
>       et mis les pipelines groupés à la racine de tasks mais c'est qu'une proposition

OK, je te laisse terminer, je regarderai demain 🥱... et on reparle demain à 19h en visio si tu es dispo.

2024-03-27 20:37 UTC, njouanin approved these changes

2024-03-28 22:50 UTC, rv2931 commented
J'ai corrigé des erreurs de syntaxe Union
Mis à jour la dock et le chargement de via docker-compose-load-data pour les tasks init & pipeline_ais_data

Par contre je termine mon chargement avec une erreur
bloom-load-data  | (psycopg2.errors.ForeignKeyViolation) insert or update on table "spire_vessel_positions" violates foreign key constraint "fk_spire_vessel_positions_vessels"
bloom-load-data  | DETAIL:  Key (vessel_id)=(1431) is not present in table "vessels".

Y aurait un problème dans l'ordonnancement des tâches ou bien dans les fichier CSV ? @njouanin a ton avis ?

2024-03-28 23:59 UTC, rv2931 commented
je pense qu'il y a un micmac entre la table vessel et la table dim_vessel
On est d'accord: 
- qu'il faut utiliser vessel_subset.csv ?
- que ce fichier est chargé directement dans dim_vessel ?
- qu'on charge les positions avec load_spire_data_from_api ?
- que load_spire_data_from_api doit chercher ses vessel dans dim_vessel et non dans la table vessel ? => si oui ce n'est pas le ca actuellement donc le chargement des positions se fini avec une erreur que le vessel 1431 n'existe pas dans vessel, effectivement il est dans dim_vessel
J'ai bon ou j'ai faux ?

2024-03-29 18:34 UTC, njouanin commented
> je pense qu'il y a un micmac entre la table vessel et la table dim_vessel On est d'accord:
> 
>     * qu'il faut utiliser vessel_subset.csv ?
Oui
> 
>     * que ce fichier est chargé directement dans dim_vessel ?
oui, via le traitement `load_dim_vessel_from_csv.py`
> 
>     * qu'on charge les positions avec load_spire_data_from_api ?
oui, via le traitement `load_spire_data_from_api.py`
> 
>     * que load_spire_data_from_api doit chercher ses vessel dans dim_vessel et non dans la table vessel ? => si oui ce n'est pas le ca actuellement donc le chargement des positions se fini avec une erreur que le vessel 1431 n'existe pas dans vessel, effectivement il est dans dim_vessel
>       J'ai bon ou j'ai faux ?

2024-03-29 20:52 UTC, njouanin requested changes

2024-03-29 20:52 UTC, njouanin commented on src/tasks/dimensions/load_dim_vessel_from_csv.py
> +            id=int(row['id']),
c'est dangereux de reprendre l'id qui vient du fichier CSV. On a un risque de conflit avec la PK de la table. Il vaut mieux ignorer cet id et laisser la base initialisé les identifiants uniques.

2024-03-29 20:55 UTC, rv2931 commented on src/tasks/dimensions/load_dim_vessel_from_csv.py
> +            id=int(row['id']),
Oui je suis d'accord mais alors fait le faire sur le clé naturelle (mmsi) mais je pense que j'avais un souci avec ça du fait d'utiliser la mauvaise task

2024-03-30 09:02 UTC, njouanin commented
Peut-être pour une prochaine évolution, mais pourrait-on améliorer la visibilité du logging:
 - rendre plus visible l'exécution des différentes étapes
 - marquer le début/fin de chaque étape (+ temps d'exécution)

Pourquoi pas ? pousser les log dans un channel slack....

2024-04-01 07:54 UTC, njouanin approved these changes

2025-01-26 19:34 UTC, closed without merging