proosition reogranisation répertoire pour front/back/etl
dataforgoodfr/12_bloom pull request #153
Opened 2024-04-06 08:43 UTC by rv2931

2024-04-07 12:32 UTC, rv2931 commented
@njouanin @tanega 
Tant qu'à faire une réorganisation, je sortirais bien tout ce qui est ETL de la partie backend/bloom actuelle dans le sens ou l'ETL n'est pas forcément à être exécuté sur la machine backend (c'est même plutôt déconseillé) et à l'avenir tout ce qui est ETL pourrait se faire avec d'autres outils
Pour le moment ça concerne principalement e système de "tasks" que nico a mis en place et que j'ai commencé à structurer un peu plus pour pouvoir faire des pipelines avec gestion des erreurs et tracing
qu'en pensez-vous ?

2024-04-07 13:10 UTC, rv2931 commented
@tanega effectivement, compte tenu du fait que ça ne sera pas forcément les mêmes technos entre back et front au final, je trouve pas mal ta proposition d'avoir un répertoire backend et frontend à minima à la racine plutôt que src/backend et src/frontend comme je le proposais. ça permet en plus d'y intégrer les fichiers projets (projecttoml, almebic et autres) au niveau du backend spécifiquement plutôt que de mélanger tout

2024-04-07 15:17 UTC, njouanin commented
OK pour moi.
sur la partie streamlit, elle est obsolète, il faudra dégager le code en même temps qu'on supprimera les anciennes tables.

2024-04-08 06:41 UTC, rv2931 commented
Pour le moment j'ai fait un mono-conteneur qui permet de lancer et le serveur back et le service front et qui premettra éventuellement de lancer le service API si on le fait (au moins pour simuler l'API côté front).
j'utilise le serveur de dev de Next.JS, je pense pas que ce soit hyper conseillé mais je connais pas trop Next.js donc pour le moment comme on est en dev...

2024-04-10 16:50 UTC, tanega commented
@rv2931 merci pour cette proposition de réorganisation du projet ! En l'état ça me va bien, très bien même ;)

2024-04-15 14:17 UTC, rv2931 commented
ok
Je rebase et je resteste ce que je peux
@tanega Je suis pas au clair de comment tu charge tes données pour éventuellement tester la partie front. Tu peux me guider un peu ?

2024-04-16 10:11 UTC, rv2931 commented
Ach .. je suis embêté la réorganisation Backend/Frontend a tout cassé la partie poetry et la partie tox
A priori tox aime pas trop avoir des sous répertoires et poetry est configuré pour générer un package bloom et donc avoir un dossier bloom
Quand je mets poetry en mode non-package, sur l'idée que ça n'a peut être plus trop de sens de faire un package bloom puisque le front ne sera pas en python, la ça casse les tests d'une autre manière...

2024-04-19 15:16 UTC, njouanin requested changes
J'ai l'impression que cette PR n'est pas basée sur les derniers changements de main. Sauf erreur de ma part j'ai mergé récemment la suppresion de pas mal de code obsolète (tables de l'ancien modèle, streamlit,...)

2024-04-19 15:16 UTC, njouanin commented on README.md
> +    streamlit run front_streamlit/Trawlwatcher.py
A  supprimer, on n'a plus d'app streamlit

2024-04-19 15:16 UTC, njouanin commented on trawlwatch-backend/trawlwatch-backend/infra/database/sql_model.py
> -    details = Column("details", String)
ces colonnes sont à conserver

2024-04-19 15:16 UTC, njouanin commented on trawlwatch-backend/trawlwatch-backend/infra/database/sql_model.py
> +class VesselPositionSpire(Base):
il me semblait avoir merger sur main la suppression de cette classe...

2024-04-20 12:18 UTC, njouanin approved these changes

2024-04-20 12:19 UTC, rv2931 commented
@njouanin @tanega 
ça devrait être bon
Les tests tox fonctionnent mieux j'ai été moins loin dans le réorg et je n'ai donc pas cassé l'architecture attendue par poetry pour le package bloom
Il y le test test_vessel_is_in_port qui fail,

2024-04-20 12:24 UTC, rv2931 commented
Pour un test côté Front
* récupérer le fichier de Gaetan : https://data-for-good.slack.com/files/U065EKU1UES/F06V7AYE2G4/data-frontend-v2.tar.gz
* décompresser toutes les données et faire en sorte qu'elles se retrouvent dans <project>/data/geometries avec 3 json dedans
* docker compose build
* docker compose up    (accessoirement j'ai poussé mes scripts ./docker/up.sh et docker/up.bat, idem pour le dev ./docker/dev/up.sh|bat)
* naviguer sur http://localhost:3000

2024-04-20 12:28 UTC, njouanin commented
il doit manquer du nettoyage. Pourquoi on a encore du code dans `src/` (et que l'on retrouve également apparemment dans `backend/`

2024-04-20 12:29 UTC, njouanin commented
```
$python3 backend/tasks/facts/extract_spire_data_from_api.py
Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/backend/tasks/facts/extract_spire_data_from_api.py", line 7, in <module>
    from bloom.container import UseCases
ModuleNotFoundError: No module named 'bloom.container'
```

2024-04-20 13:27 UTC, rv2931 commented
> il doit manquer du nettoyage. Pourquoi on a encore du code dans `src/` (et que l'on retrouve également apparemment dans `backend/`
il n'y plus rien dans src, je pense que soit il est vide et le dossier n'a pas été supprimé, soit c'est un reste de checkout entre branches
https://github.com/dataforgoodfr/12_bloom/tree/folder_reorg_back_front

2024-04-20 13:28 UTC, rv2931 commented
> .container'

Ah oui, j'ai oublié de rajouter les PYTHONPATH=${PROJECT_DIR}/backend

2024-04-20 13:34 UTC, njouanin commented
> > il doit manquer du nettoyage. Pourquoi on a encore du code dans `src/` (et que l'on retrouve également apparemment dans `backend/`
> > il n'y plus rien dans src, je pense que soit il est vide et le dossier n'a pas été supprimé, soit c'est un reste de checkout entre branches
> > https://github.com/dataforgoodfr/12_bloom/tree/folder_reorg_back_front

OK, il reste effectivement des répertoires dans src, mais vides.

2024-04-20 13:39 UTC, njouanin commented
> > .container'
> 
> Ah oui, j'ai oublié de rajouter les PYTHONPATH=${PROJECT_DIR}/backend Désolé, c'est corrigé... j'avais pas testé les tâches :(

Je ne lance pas depuis docker, mais directement en ligne de commande.

2024-04-20 13:48 UTC, rv2931 commented
Je ne sais plus si le répertoire courant est pris automatiquement dans le
pythonpath
Si oui faut que je rajoute du backend.bloom... pour tous les imports ou
bien un cd ./backend dans la doc du lancement en natif... Ou encore un
export <project>/backend avant lancement

Le sam. 20 avr. 2024, 15:39, Nicolas ***@***.***> a écrit :

> .container'
>
> Ah oui, j'ai oublié de rajouter les PYTHONPATH=${PROJECT_DIR}/backend
> Désolé, c'est corrigé... j'avais pas testé les tâches :(
>
> Je ne lance pas depuis docker, mais directement en ligne de commande.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dataforgoodfr/12_bloom/pull/153#issuecomment-2067677551>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADLDQDUIUGDJ2M6TNVBIPMDY6JVZXAVCNFSM6AAAAABF2IYQEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANRXGY3TONJVGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-20 13:50 UTC, rv2931 commented
A priori on peut mettre a jour le pythonpath directement dans le code. Je
pense que je vais faire ça
https://python.doctor/page-python-path-pythonpath

Le sam. 20 avr. 2024, 15:48, Hervé LE BARS ***@***.***> a écrit :

> Je ne sais plus si le répertoire courant est pris automatiquement dans le
> pythonpath
> Si oui faut que je rajoute du backend.bloom... pour tous les imports ou
> bien un cd ./backend dans la doc du lancement en natif... Ou encore un
> export <project>/backend avant lancement
>
> Le sam. 20 avr. 2024, 15:39, Nicolas ***@***.***> a écrit :
>
>> .container'
>>
>> Ah oui, j'ai oublié de rajouter les PYTHONPATH=${PROJECT_DIR}/backend
>> Désolé, c'est corrigé... j'avais pas testé les tâches :(
>>
>> Je ne lance pas depuis docker, mais directement en ligne de commande.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/dataforgoodfr/12_bloom/pull/153#issuecomment-2067677551>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADLDQDUIUGDJ2M6TNVBIPMDY6JVZXAVCNFSM6AAAAABF2IYQEWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANRXGY3TONJVGE>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2024-04-20 20:10 UTC, rv2931 commented
@njouanin sinon tu me confirmes que ça fonctionne en te mettant dans le dossier backend ?

2024-04-20 20:18 UTC, njouanin commented
> @njouanin sinon tu me confirmes que ça fonctionne en te mettant dans le dossier backend ?

Ni l'un , ni l'autre:
```
$ python3 backend/tasks/facts/extract_spire_data_from_api.py
Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/backend/tasks/facts/extract_spire_data_from_api.py", line 7, in <module>
    from bloom.container import UseCases
ModuleNotFoundError: No module named 'bloom.container'
$ cd backend
$ python3 tasks/facts/extract_spire_data_from_api.py
Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/backend/tasks/facts/extract_spire_data_from_api.py", line 7, in <module>
    from bloom.container import UseCases
ModuleNotFoundError: No module named 'bloom.container'
```

2024-04-20 21:06 UTC, rv2931 commented
tu peux réssayer avec tes taches backend/bloom/tasks ? j'avais intégré par erreur les set de tasks que j'ai migré mais dans cette PR c'était pas l'objet

2024-04-21 09:03 UTC, njouanin commented
J'ai corrigé les noms de modules (ajout de `backend`) dans les import.
Par contre ça ne fonctionne toujours pas si je n'ajoute pas PYTHONPATH. Ça marchait sans avant ...

2024-04-21 09:33 UTC, rv2931 commented
> ne fonctionne toujours pas si je n'ajoute

Moi j'arrive pas à reproduire le problème :(
De base pour Python tu dois rajouter le répertoires ou les répertoires de ton projet pour y accéder an tant que module
Pour les mêmes raisons que Linux n'exécute pas les exécutables du dossier courant, ce serait une faille de sécurité de charger le module du dossier courant à la place d'un module installé dans les sites-packages de python
L'autre solution c'est d'accéder aux modules de ton projet en utiliser le .backend/... en chemin relatif mais idem, il lui faut une référence absolue qui se trouve dans les PYTHONPATH par défaut ou exporté explicitement
Donc j'ai tendance à dire que si ça fonctionnait avant sans avoir de variable PYTHONPATH c'est pas tout à fait normal. Maintenant selon les implémentaitons Windows/Linux peut-être qu'il prend le chemin courant automatiquement
De mon côté, en faisant un cd backend et python bloom/tasks/load_dim_port... ben,... ça fonctionne, et je comprends pas trop pourquoi

2024-04-21 09:38 UTC, rv2931 commented
Après j'aurais tendance à dire que c'est plus propre de bien scinder les choses à savoir, tu veux travailler dans le backend, tu fais un "cd backend pour que ça fonctionne" idem pour le frontend, sachant qu'il y aura potentiellement un 3ème projet pour la partie interface/API qui oit pouvoir se faire avec une autre techno... ou pas, mais qui doit idéalement être indépendante et du backend et du frontend

2024-04-21 12:01 UTC, njouanin commented
OK, vas-y comme ça. Tu peux merger, c'est bon pour moi.

2024-04-21 21:41 UTC, rv2931 commented
@tanega @njouanin 
De mon côté la réorg est bonne par contre deux soucis côté github actions:
- j'ai désactivé la commande pytest dans tox car le `test_vessel_in_port `nécessite une base de donnée hors il n'y en a aucune de configurée à priori côté github et je ne maitrise pas assez pour le configurer
- J'ai une erreur de build spécifiquement avec un build côté github ci/cd sur le frontend `Module not found: Can't resolve '@/lib/stores/map-store'` visible ici https://github.com/dataforgoodfr/12_bloom/actions/runs/8775573948/job/24078222932?pr=153

Je ne sais pas résoudre ces problèmes mais ils ne sont pas liés à la réorg de dossiers

2024-04-22 20:48 UTC, merged