Changes in dim_vessel et dim_vessel data
dataforgoodfr/12_bloom pull request #161
Opened 2024-04-07 21:18 UTC by sarahlunette

Update in 
src/bloom/infra/database/sql_model.py
src/bloom/infra/r…/repository_vessel.py
src/blo…/load_dim_vessel_from_csv.py
src/alembic/versio…sel_data_tables.py
41c412cf8175_create_dim_vessel
src/bloom/domain/vessel.py
src/bloom/domain/vessel_data.py
src/bloom/…/repository_vessel_data.py

pour l'ajout d'un comment column

2024-04-08 19:32 UTC, njouanin requested changes
En résumé:
- renommer la colonne `comment` en `details`
- pas de changement à faire sur la table vessel_data
- ne pas modifier les scripts de migration existant, mais en ajouter un nouveau

2024-04-08 19:32 UTC, njouanin commented on .DS_Store
A supprimer

2024-04-08 19:32 UTC, njouanin commented on data/.DS_Store
A supprimer

2024-04-08 19:32 UTC, njouanin commented on src/.DS_Store
A supprimer

2024-04-08 19:32 UTC, njouanin commented on src/alembic/versions/2d54ea045ff3_create_vessel_data_tables.py
> +        sa.Column('comment', sa.String)
La table vessel_data n'est pas à modifier

2024-04-08 19:32 UTC, njouanin commented on src/alembic/versions/41c412cf8175_create_dim_vessel.py
> +        sa.Column("comment", sa.String),
Dans l'issue #147, Marthe souhaite que la colonne se nomme `details`. 
Par ailleurs, ne pas modifier les migrations existances, mais ajouter une nouvelle migration avec la commande:
`alembic revision -m "add_dim_vessel_comment"`

2024-04-08 19:32 UTC, njouanin commented on src/bloom/domain/vessel.py
> +    comment: str
cf. plus haut, à renommer en `details`
et à initialiser de la façon suivante (champ optionnel) :
```
comment: Union[str None] = None
```

2024-04-08 19:32 UTC, njouanin commented on src/bloom/domain/vessel_data.py
pas de changement attendu dans vessel_data

2024-04-08 19:32 UTC, njouanin commented on src/bloom/infra/database/sql_model.py
> +    comment = Column("comment", String)
pas de changement attendu sur vessel_data

2024-04-08 19:32 UTC, njouanin commented on src/bloom/infra/repositories/repository_vessel_data.py
> +            commenr=data.comment
pas de changement attendu sur vessel_data

2024-04-08 19:32 UTC, njouanin commented on src/bloom/infra/repositories/repository_vessel_data.py
> +            comment=data.comment
pas de changement attendu sur vessel_data

2024-04-08 19:37 UTC, njouanin requested changes

2024-04-08 19:37 UTC, njouanin commented on src/alembic/versions/41c412cf8175_create_dim_vessel.py
Ne pas modifier les scripts existant => créer un nouveau script avec `alembic revision -m ...`

2024-04-08 19:37 UTC, njouanin commented on src/bloom/infra/.DS_Store
A supprimer

2024-04-08 20:13 UTC, sarahlunette commented on src/alembic/versions/41c412cf8175_create_dim_vessel.py
> +        sa.Column("comment", sa.String),
Salut, je ne sais pas où mettre cette révision

2024-04-08 20:14 UTC, sarahlunette commented on src/bloom/domain/vessel.py
> +    comment: str
ok

2024-04-08 20:39 UTC, sarahlunette reviewed
Corrections on my mistakes

2024-04-08 20:39 UTC, sarahlunette commented on src/alembic/versions/2d54ea045ff3_create_vessel_data_tables.py
> +        sa.Column('comment', sa.String)
J'ai enlevé la ligne 74

2024-04-08 20:39 UTC, sarahlunette commented on src/alembic/versions/41c412cf8175_create_dim_vessel.py
Où est-ce qu'on met cette commande ?

2024-04-08 20:39 UTC, sarahlunette commented on src/alembic/versions/41c412cf8175_create_dim_vessel.py
> +        sa.Column("comment", sa.String),
J'ai remplacé comment par details

2024-04-08 20:39 UTC, sarahlunette commented on src/bloom/domain/vessel_data.py
Ok

2024-04-08 20:39 UTC, sarahlunette commented on src/bloom/infra/database/sql_model.py
> +    comment = Column("comment", String)
ok

2024-04-08 20:39 UTC, sarahlunette commented on src/bloom/infra/repositories/repository_vessel_data.py
> +            commenr=data.comment
ok

2024-04-09 07:51 UTC, njouanin commented on src/alembic/versions/41c412cf8175_create_dim_vessel.py
la commande `alembic revision -m "add_dim_vessel_comment"` va créer un nouveau script dans le répertoire alembic/versions. C'est dans ce nouveau script que tu dois coder les commandes d'alter up et down de la table.
Ensuite `alemebic upgrade head` pour appliquer les changements.
Voir la [doc alembic](https://alembic.sqlalchemy.org/en/latest/) pour plus de détail.

2024-04-09 07:52 UTC, njouanin commented on .DS_Store
A supprimer.

2024-04-09 07:52 UTC, njouanin commented on src/.DS_Store
A supprimer

2024-04-09 07:53 UTC, njouanin commented on src/bloom/.DS_Store
A supprimer (ne pas comiter ces fichiers)

2024-04-09 07:53 UTC, njouanin commented on src/bloom/domain/vessel.py
> +    details: Union[str None] = None
il manque une `,` entre `str None`

2024-04-09 07:55 UTC, njouanin requested changes
Commentaires à prendre en compte
 - ajout d'un script de migration alembic
 - suppression des fichiers .DS_Store

2024-04-10 19:13 UTC, njouanin approved these changes

2024-04-10 19:16 UTC, njouanin approved these changes

2024-04-10 19:16 UTC, merged