Issue155 etl clean positions
dataforgoodfr/12_bloom pull request #167
Opened 2024-04-13 09:43 UTC by hehlinge42

Ajout de l'ETL clean_positions : 

J'ai dû modifier pas mal de fichiers pour créer les requêtes, j'espère avoir fait correctement, sinon je serai preneur d'un retour.

Quelques points restent à valider avant de fusionner : 
- J'ai réalisé un test unitaire sur un faux batch spire de 10 lignes de données. Le script src/bloom/tasks/load_fct_excursions_from_csv.py permet de monter cette donnée dans la DB. Est-ce que je push ce test unitaire dans la branche (et le script de loading associé) ou est-ce que je le supprime ?
- Quelle est l'unité attendue pour la vitesse dans la table vessel_positions ? Actuellement je l'ai calculée en km/h mais peut être pour des bateaux, les noeuds seraient plus appropriés
- Quelle est la colonne de timestamp à utiliser depuis la table spire_ais_data pour faire les calculs de vitesse ? J'ai pris position_timestamp mais il y a aussi spire_update_statement et position_update_timestamp
- Est-ce que l'ancien code de clean_positions doit être gardé ou est-ce que je le supprime aussi ?

PS : désolé pour certains changements de pure forme, j'ai le formatteur black qui tourne automatiquement sur mon VS Code.

2024-04-13 09:45 UTC, hehlinge42 commented
Je vois qu'il y a des conflits dans 3 fichiers aussi, j'ai tiré la branche samedi dernier j'imagine qu'il y a eu des changements entre temps dans le main

2024-04-13 10:10 UTC, njouanin commented
> Je vois qu'il y a des conflits dans 3 fichiers aussi, j'ai tiré la branche samedi dernier j'imagine qu'il y a eu des changements entre temps dans le main

Oui il faudrait d'abord que tu merge les changements de main qui ont eu lieu depuis que tu as tiré la branche.

2024-04-13 10:55 UTC, Myekah commented
Vitesse en noeud, distance en mile marin. Pour le timestamp je n'arrive pas à retenir la diff entre timestamp et update_timestamp, voir avec nico. Pour l'ancien code, à mon avis tu peux le virer, mais si tu as des doutes laisse le juste en commentaire.

2024-04-13 19:47 UTC, njouanin commented
> Vitesse en noeud, distance en mile marin. Pour le timestamp je n'arrive pas à retenir la diff entre timestamp et update_timestamp, voir avec nico. Pour l'ancien code, à mon avis tu peux le virer, mais si tu as des doutes laisse le juste en commentaire.

timestamp = horodatage de la donnée AIS envoyée par le navire
update_timestamp = horodatage de prise en compte de la données AIS par SPIRE

=> il faut utiliser le timestamp qui correspond au plus plus près de la donnée transmise par le navire.

2024-04-13 20:05 UTC, njouanin requested changes

2024-04-13 20:05 UTC, njouanin commented on src/bloom/tasks/clean_positions.py
> +            (row["longitude"], row["latitude"]),
j'ai l'impression que le dataframe `batch` n'a pas de colonnes `longitude` et `latitude`. En lançant la traitement j'ai erreur suivante:
```
Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'longitude'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/src/bloom/tasks/clean_positions.py", line 171, in <module>
    run()
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/src/bloom/tasks/clean_positions.py", line 113, in run
    batch["distance_since_last_position"] = batch.apply(
                                            ^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/frame.py", line 10361, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/apply.py", line 916, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/apply.py", line 1063, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/apply.py", line 1081, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/src/bloom/tasks/clean_positions.py", line 116, in <lambda>
    (row["longitude"], row["latitude"]),
     ~~~^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 1112, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/series.py", line 1228, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/bloom/12_bloom/.venv/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'longitude'
```

2024-04-14 08:48 UTC, hehlinge42 commented on data/ports.csv
C'est une erreur liée au merge. Comme le .gitignore ignore tous les data/*.csv. Je le remets et change le gitignore.

2024-04-14 08:49 UTC, hehlinge42 commented on data/updated_vessels_table.csv
Idem

2024-04-14 08:54 UTC, hehlinge42 commented on src/bloom/tasks/clean_positions.py
> +            (row["longitude"], row["latitude"]),
J'ai compris. Les colonnes longitude et latitude sont créées dans la lambda function to_coords à partir du champs "end_position" de la table segment si et seulement si celui-ci est non-NULL. Il y avait un corner case où tous les "end_position" de la requête à fct_segment sont null auquel cas les 2 colonnes n'étaient jamais créées. J'ai corrigé en initialisant les colonnes avant la lambda

2024-04-15 19:17 UTC, njouanin approved these changes

2024-04-16 06:58 UTC, merged